apiVersion: v1
kind: Service
metadata:
  name: kubeservice
spec:
  selector:
    app: kubeuser
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeusers
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kubeusers
  template:
    metadata:
      labels:
        app: kubeusers
    spec:
      containers:
      - name: kubecontainer
        image: defe014/usercreator39750:1.0.0
        ports:
          - containerPort: 8080
        env:
          - name: MONGO_URL
            value: mongo+srv
        imagePullPolicy: Always
